version: '3.0'
services:
  hub:
    # container_name: hub
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  # node-firefox:
  #   image: selenium/node-firefox
  #   links:
  #     - hub
  #   expose:
  #     - "5555"
  # node-chrome:
  #   image: selenium/node-chrome
  #   links:
  #     - hub
  #   expose:
  #     - "5555"
  # node-firefox-debug:
    # image: selenium/node-firefox-debug:latest
    # environment:
      # - HUB_PORT_4444_TCP_ADDR=172.18.0.3
      # - HUB_PORT_4444_TCP_PORT=4444
      # - no_proxy=
    # expose:
    #   - "5555"
    # ports:
    #   - "5900:5900"
  node-chrome-debug:
    image: selenium/node-chrome-debug:latest
    environment:
      - HUB_PORT_4444_TCP_ADDR=172.18.0.3
      - HUB_PORT_4444_TCP_PORT=4444
      - no_proxy=
    expose:
      - "5555"
    ports:
      - "5900:5900"
