hub:
  image: selenium/hub
  ports:
    - "4444:4444"
node-firefox:
  image: selenium/node-firefox
  links:
    - hub
  expose:
    - "5555"
node-chrome:
  image: selenium/node-chrome
  links:
    - hub
  expose:
    - "5555"
node-firefox-debug:
  image: selenium/node-firefox
  links:
    - hub
  expose:
    - "5555"
  ports:
    - "5900:5900"
node-chrome-debug:
  image: selenium/node-chrome
  links:
    - hub
  expose:
    - "5555"
  ports:
    - "5901:5900"
